# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wqi_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(60, 110, 113);\n"
"}\n"
"QLabel{\n"
"    color: white;\n"
"    font: 63 18pt \"Segoe UI Black\"\n"
"}\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 63 10pt \"Segoe UI Black\";\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/logo_app.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_menu_title = QtWidgets.QLabel(self.frame_menu)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_menu_title.setFont(font)
        self.label_menu_title.setStyleSheet("")
        self.label_menu_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menu_title.setObjectName("label_menu_title")
        self.verticalLayout_2.addWidget(self.label_menu_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_menu_load = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_menu_load.setMaximumSize(QtCore.QSize(16777215, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icon_pushbutton_upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_menu_load.setIcon(icon)
        self.pushButton_menu_load.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_menu_load.setFlat(False)
        self.pushButton_menu_load.setObjectName("pushButton_menu_load")
        self.verticalLayout_2.addWidget(self.pushButton_menu_load)
        self.pushButton_menu_download = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_menu_download.setMaximumSize(QtCore.QSize(16777215, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/icon_pushbutton_download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_menu_download.setIcon(icon1)
        self.pushButton_menu_download.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_menu_download.setObjectName("pushButton_menu_download")
        self.verticalLayout_2.addWidget(self.pushButton_menu_download)
        self.pushButton_menu_config = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_menu_config.setMaximumSize(QtCore.QSize(16777215, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/icon_pushbutton_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_menu_config.setIcon(icon2)
        self.pushButton_menu_config.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_menu_config.setObjectName("pushButton_menu_config")
        self.verticalLayout_2.addWidget(self.pushButton_menu_config)
        spacerItem2 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(self.frame_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 2)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(60, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/logo_GIAQA_blanca.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(63, 68))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("resources/logo_UNS_blanco.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 4)
        self.verticalLayout_2.setStretch(5, 4)
        self.verticalLayout_2.setStretch(6, 4)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 2)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(53, 53, 53);\n"
"    font: 63 10pt \"Segoe UI Semibold\"\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_main)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 10px; \n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    max-height: 20px; \n"
"    min-width: 40px;\n"
"    background-color: #FFFFFF; \n"
"    color: #353535;            \n"
"    border-radius: 10px;\n"
"    padding: 5px 20px;\n"
"    margin-right: 3px;\n"
"    font: 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #3C6E71;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3C6E71;\n"
"}\n"
"\n"
"/* 5. PESTAÑA AL PASAR EL MOUSE (Hover) */\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #FFFFFF;   /* Azul muy clarito */\n"
"    color: #353535;\n"
"    border: 1px solid #3C6E71;\n"
"}")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabIWQI = QtWidgets.QWidget()
        self.tabIWQI.setObjectName("tabIWQI")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabIWQI)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_control_IWQI = QtWidgets.QFrame(self.tabIWQI)
        self.frame_control_IWQI.setStyleSheet("QLabel{\n"
"    color:rgb(11, 7, 125)\n"
"    font: 75 30pt \"MS Shell Dlg 2\";\n"
"}")
        self.frame_control_IWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_control_IWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control_IWQI.setObjectName("frame_control_IWQI")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_control_IWQI)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_name_IWQI = QtWidgets.QLabel(self.frame_control_IWQI)
        self.label_name_IWQI.setText("")
        self.label_name_IWQI.setObjectName("label_name_IWQI")
        self.horizontalLayout_4.addWidget(self.label_name_IWQI)
        spacerItem3 = QtWidgets.QSpacerItem(725, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_control_AX2_IWQI = QtWidgets.QLabel(self.frame_control_IWQI)
        self.label_control_AX2_IWQI.setObjectName("label_control_AX2_IWQI")
        self.horizontalLayout_4.addWidget(self.label_control_AX2_IWQI)
        self.comboBox_IWQI = QtWidgets.QComboBox(self.frame_control_IWQI)
        self.comboBox_IWQI.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;         /* Borde totalmente circular (Cápsula) */\n"
"    padding: 4px 10px 4px 10px;  /* Más padding a la izq para el texto */\n"
"    color: #353535;\n"
"    font: 63 9pt \"Segoe UI Semilight\";\n"
"}\n"
"\n"
"/* Efecto al pasar el mouse por encima */\n"
"QComboBox:hover {\n"
"    border: 1px solid #3C6E71;   /* Se pone azul el borde */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Cuando está desplegado */\n"
"QComboBox:on { \n"
"    border-bottom-left-radius: 0px;  /* Quitamos curvas de abajo para conectar con la lista */\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* 1. EL BOTÓN CUADRADO DE LA DERECHA */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px; /* Ancho del área clickeable */\n"
"    \n"
"    border-left-width: 0px; /* Sin línea divisoria */\n"
"    border-top-right-radius: 10px; /* Redondeamos igual que el combo */\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: transparent; /* ¡Vital! Para que no se vea un parche de color */\n"
"}\n"
"\n"
"/* 2. LA IMAGEN DE LA FLECHA */\n"
"QComboBox::down-arrow {\n"
"    /* Reemplaza \'assets/flecha_abajo.png\' con tu ruta real */\n"
"    image: url(C:/Users/Cachi/Desktop/WQI Calculator/resources/combobox_arrow_down.png);\n"
"    \n"
"    \n"
"    width: 10px;   /* Tamaño pequeño para elegancia */\n"
"    height: 10px;\n"
"    \n"
"    /* Centrado y márgenes */\n"
"    content: \"\";   /* A veces ayuda a limpiar residuos */\n"
"    margin-right: 10px; /* Separación del borde derecho */\n"
"}\n"
"\n"
"/* 3. (Opcional) EFECTO AL ABRIR */\n"
"/* Si tu flecha es negra, quizás no necesites cambiarla, \n"
"   pero si quisieras rotarla o cambiarla, usarías esto */\n"
"QComboBox::down-arrow:on {\n"
"    /* Podrías poner otra imagen: url(assets/flecha_arriba.png); */\n"
"    /* O moverla ligeramente para dar efecto de \"click\" */\n"
"    top: 1px; \n"
"    left: 1px;\n"
"}")
        self.comboBox_IWQI.setObjectName("comboBox_IWQI")
        self.horizontalLayout_4.addWidget(self.comboBox_IWQI)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 3)
        self.verticalLayout.addWidget(self.frame_control_IWQI)
        self.frame_plot_IWQI = QtWidgets.QFrame(self.tabIWQI)
        self.frame_plot_IWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_plot_IWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_IWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_IWQI.setObjectName("frame_plot_IWQI")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_plot_IWQI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_plot_IWQI = QtWidgets.QWidget(self.frame_plot_IWQI)
        self.widget_plot_IWQI.setEnabled(True)
        self.widget_plot_IWQI.setObjectName("widget_plot_IWQI")
        self.verticalLayout_4.addWidget(self.widget_plot_IWQI)
        self.verticalLayout.addWidget(self.frame_plot_IWQI)
        self.frame_other_IWQI = QtWidgets.QFrame(self.tabIWQI)
        self.frame_other_IWQI.setStyleSheet("")
        self.frame_other_IWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_other_IWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_other_IWQI.setObjectName("frame_other_IWQI")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_other_IWQI)
        self.horizontalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_table_IWQI = QtWidgets.QFrame(self.frame_other_IWQI)
        self.frame_table_IWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_table_IWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_table_IWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_table_IWQI.setObjectName("frame_table_IWQI")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_table_IWQI)
        self.verticalLayout_3.setContentsMargins(9, 5, 9, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_IWQI = QtWidgets.QTableWidget(self.frame_table_IWQI)
        self.tableWidget_IWQI.setEnabled(True)
        self.tableWidget_IWQI.setStyleSheet("QTableView {\n"
"    background-color: #FFFFFF;     \n"
"    gridline-color: transparent;   \n"
"    selection-background-color: #E3F2FD; \n"
"    selection-color: #1565C0;     \n"
"    font-size: 12px;\n"
"    outline: 0; \n"
"}\n"
"\n"
"\n"
"QTableView::item {\n"
"    border-bottom: 1px solid #F0F0F0; \n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    border: none;\n"
"    background-color: #E3F2FD;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: #FAFAFA; \n"
"}\n"
"\n"
"/* 3. LOS ENCABEZADOS (HEADERS) */\n"
"QHeaderView::section {\n"
"\n"
"    background-color: #FFFFFF;    \n"
"    color: #3C6E71;              \n"
"    border: 2px solid #D9D9D9;     \n"
"\n"
"    border-radius: 15px;          \n"
"    margin: 1px 1px;               /* Separamos los headers entre sí (Arriba/Abajo, Izq/Der) */\n"
"    padding: 1px 1px;             /* Relleno para que el texto respire */\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"/* 5. SCROLLBAR VERTICAL (Minimalista) */\n"
"QScrollBar:vertical {\n"
"    background: #F5F5F5;\n"
"    width: 8px;               /* Muy delgada */\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;      /* Gris suave */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;       /* Redondeada */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #999999;      /* Un poco más oscuro al pasar mouse */\n"
"}\n"
"\n"
"/* Ocultar flechas de arriba y abajo del scroll para limpieza total */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableWidget_IWQI.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_IWQI.setObjectName("tableWidget_IWQI")
        self.tableWidget_IWQI.setColumnCount(7)
        self.tableWidget_IWQI.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Muestra")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Na⁺")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Cl⁻")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("HCO₃⁻")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("RAS")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("EC")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("IWQI")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_IWQI.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget_IWQI)
        self.horizontalLayout_3.addWidget(self.frame_table_IWQI)
        self.frame_percents_IWQI = QtWidgets.QFrame(self.frame_other_IWQI)
        self.frame_percents_IWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_percents_IWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_percents_IWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_percents_IWQI.setObjectName("frame_percents_IWQI")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_percents_IWQI)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_percents_IWQI = QtWidgets.QWidget(self.frame_percents_IWQI)
        self.widget_percents_IWQI.setObjectName("widget_percents_IWQI")
        self.verticalLayout_5.addWidget(self.widget_percents_IWQI)
        self.horizontalLayout_3.addWidget(self.frame_percents_IWQI)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_other_IWQI)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        self.verticalLayout.setStretch(2, 6)
        self.tabWidget.addTab(self.tabIWQI, "")
        self.tabDWQI = QtWidgets.QWidget()
        self.tabDWQI.setObjectName("tabDWQI")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabDWQI)
        self.verticalLayout_9.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_control_DWQI = QtWidgets.QFrame(self.tabDWQI)
        self.frame_control_DWQI.setStyleSheet("QLabel{\n"
"    color:rgb(11, 7, 125)\n"
"    font: 75 30pt \"MS Shell Dlg 2\";\n"
"}")
        self.frame_control_DWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_control_DWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control_DWQI.setObjectName("frame_control_DWQI")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_control_DWQI)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_name_DWQI = QtWidgets.QLabel(self.frame_control_DWQI)
        self.label_name_DWQI.setText("")
        self.label_name_DWQI.setObjectName("label_name_DWQI")
        self.horizontalLayout_6.addWidget(self.label_name_DWQI)
        spacerItem4 = QtWidgets.QSpacerItem(598, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_control_AX2_DWQI = QtWidgets.QLabel(self.frame_control_DWQI)
        self.label_control_AX2_DWQI.setObjectName("label_control_AX2_DWQI")
        self.horizontalLayout_6.addWidget(self.label_control_AX2_DWQI)
        self.comboBox_DWQI = QtWidgets.QComboBox(self.frame_control_DWQI)
        self.comboBox_DWQI.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;         /* Borde totalmente circular (Cápsula) */\n"
"    padding: 4px 10px 4px 10px;  /* Más padding a la izq para el texto */\n"
"    color: #353535;\n"
"    font: 63 9pt \"Segoe UI Semilight\";\n"
"}\n"
"\n"
"/* Efecto al pasar el mouse por encima */\n"
"QComboBox:hover {\n"
"    border: 1px solid #3C6E71;   /* Se pone azul el borde */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Cuando está desplegado */\n"
"QComboBox:on { \n"
"    border-bottom-left-radius: 0px;  /* Quitamos curvas de abajo para conectar con la lista */\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* 1. EL BOTÓN CUADRADO DE LA DERECHA */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px; /* Ancho del área clickeable */\n"
"    \n"
"    border-left-width: 0px; /* Sin línea divisoria */\n"
"    border-top-right-radius: 10px; /* Redondeamos igual que el combo */\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: transparent; /* ¡Vital! Para que no se vea un parche de color */\n"
"}\n"
"\n"
"/* 2. LA IMAGEN DE LA FLECHA */\n"
"QComboBox::down-arrow {\n"
"    /* Reemplaza \'assets/flecha_abajo.png\' con tu ruta real */\n"
"    image: url(C:/Users/Cachi/Desktop/WQI Calculator/resources/combobox_arrow_down.png);\n"
"    \n"
"    \n"
"    width: 10px;   /* Tamaño pequeño para elegancia */\n"
"    height: 10px;\n"
"    \n"
"    /* Centrado y márgenes */\n"
"    content: \"\";   /* A veces ayuda a limpiar residuos */\n"
"    margin-right: 10px; /* Separación del borde derecho */\n"
"}\n"
"\n"
"/* 3. (Opcional) EFECTO AL ABRIR */\n"
"/* Si tu flecha es negra, quizás no necesites cambiarla, \n"
"   pero si quisieras rotarla o cambiarla, usarías esto */\n"
"QComboBox::down-arrow:on {\n"
"    /* Podrías poner otra imagen: url(assets/flecha_arriba.png); */\n"
"    /* O moverla ligeramente para dar efecto de \"click\" */\n"
"    top: 1px; \n"
"    left: 1px;\n"
"}")
        self.comboBox_DWQI.setObjectName("comboBox_DWQI")
        self.horizontalLayout_6.addWidget(self.comboBox_DWQI)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 8)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 3)
        self.verticalLayout_9.addWidget(self.frame_control_DWQI)
        self.frame_plot_DWQI = QtWidgets.QFrame(self.tabDWQI)
        self.frame_plot_DWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_plot_DWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot_DWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot_DWQI.setObjectName("frame_plot_DWQI")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_plot_DWQI)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_plot_DWQI = QtWidgets.QWidget(self.frame_plot_DWQI)
        self.widget_plot_DWQI.setObjectName("widget_plot_DWQI")
        self.verticalLayout_6.addWidget(self.widget_plot_DWQI)
        self.verticalLayout_9.addWidget(self.frame_plot_DWQI)
        self.frame_other_DWQI = QtWidgets.QFrame(self.tabDWQI)
        self.frame_other_DWQI.setStyleSheet("")
        self.frame_other_DWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_other_DWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_other_DWQI.setObjectName("frame_other_DWQI")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_other_DWQI)
        self.horizontalLayout_5.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_table_DWQI = QtWidgets.QFrame(self.frame_other_DWQI)
        self.frame_table_DWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_table_DWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_table_DWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_table_DWQI.setObjectName("frame_table_DWQI")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_table_DWQI)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget_DWQI = QtWidgets.QTableWidget(self.frame_table_DWQI)
        self.tableWidget_DWQI.setEnabled(True)
        self.tableWidget_DWQI.setStyleSheet("QTableView {\n"
"    background-color: #FFFFFF;     \n"
"    gridline-color: transparent;   \n"
"    selection-background-color: #E3F2FD; \n"
"    selection-color: #1565C0;     \n"
"    font-size: 10px;\n"
"    outline: 0; \n"
"}\n"
"\n"
"\n"
"QTableView::item {\n"
"    border-bottom: 1px solid #F0F0F0; \n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    border: none;\n"
"    background-color: #E3F2FD;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: #FAFAFA; \n"
"}\n"
"\n"
"/* 3. LOS ENCABEZADOS (HEADERS) */\n"
"QHeaderView::section {\n"
"\n"
"    background-color: #FFFFFF;    \n"
"    color: #3C6E71;              \n"
"    border: 2px solid #D9D9D9;     \n"
"\n"
"    border-radius: 15px;          \n"
"    margin: 1px 1px;               /* Separamos los headers entre sí (Arriba/Abajo, Izq/Der) */\n"
"    padding: 1px 1px;             /* Relleno para que el texto respire */\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"/* 5. SCROLLBAR VERTICAL (Minimalista) */\n"
"QScrollBar:vertical {\n"
"    background: #F5F5F5;\n"
"    width: 8px;               /* Muy delgada */\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #CCCCCC;      /* Gris suave */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;       /* Redondeada */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #999999;      /* Un poco más oscuro al pasar mouse */\n"
"}\n"
"\n"
"/* Ocultar flechas de arriba y abajo del scroll para limpieza total */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableWidget_DWQI.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_DWQI.setObjectName("tableWidget_DWQI")
        self.tableWidget_DWQI.setColumnCount(7)
        self.tableWidget_DWQI.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Muestra")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Na⁺")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Cl⁻")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("HCO₃⁻")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("RAS")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("EC")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("IWQI")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_DWQI.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_8.addWidget(self.tableWidget_DWQI)
        self.horizontalLayout_5.addWidget(self.frame_table_DWQI)
        self.frame_percents_DWQI = QtWidgets.QFrame(self.frame_other_DWQI)
        self.frame_percents_DWQI.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.frame_percents_DWQI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_percents_DWQI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_percents_DWQI.setObjectName("frame_percents_DWQI")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_percents_DWQI)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_percents_DWQI = QtWidgets.QWidget(self.frame_percents_DWQI)
        self.widget_percents_DWQI.setObjectName("widget_percents_DWQI")
        self.verticalLayout_8.addWidget(self.widget_percents_DWQI)
        self.horizontalLayout_5.addWidget(self.frame_percents_DWQI)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_9.addWidget(self.frame_other_DWQI)
        self.verticalLayout_9.setStretch(1, 12)
        self.verticalLayout_9.setStretch(2, 6)
        self.tabWidget.addTab(self.tabDWQI, "")
        self.tabLWQI = QtWidgets.QWidget()
        self.tabLWQI.setObjectName("tabLWQI")
        self.tabWidget.addTab(self.tabLWQI, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_main)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_menu_title.setText(_translate("MainWindow", "Calculadora \n"
" WQI"))
        self.pushButton_menu_load.setText(_translate("MainWindow", "  Cargar Datos"))
        self.pushButton_menu_download.setText(_translate("MainWindow", "  Descargar"))
        self.pushButton_menu_config.setText(_translate("MainWindow", "  Configuración"))
        self.label_control_AX2_IWQI.setText(_translate("MainWindow", "Eje Secundario:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIWQI), _translate("MainWindow", "IWQI"))
        self.label_control_AX2_DWQI.setText(_translate("MainWindow", "Eje Secundario:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDWQI), _translate("MainWindow", "DWQI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLWQI), _translate("MainWindow", "LWQI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
